<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('user_details')->insert([
            [
                'user_id' => 1,
                'nin_number' => '38525458361',
                'gender' => 'male',
                'phone_number' => '123456789',
                'designation' => 'System Admin',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => null,
                'tenant_id' => 2,
            ],
            [
                'user_id' => 2,
                'nin_number' => '38625458361',
                'gender' => 'male',
                'phone_number' => '123456789',
                'designation' => 'Vice Chancellor',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 2,
                'tenant_id' => 2,
            ],
            [
                'user_id' => 3,
                'nin_number' => '39625458361',
                'gender' => 'male',
                'phone_number' => '08098776523',
                'designation' => 'Registrar',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 3,
                'tenant_id' => 3,
            ],
            [
                'user_id' => 4,
                'nin_number' => '33625458361',
                'gender' => 'male',
                'phone_number' => '0807746538',
                'designation' => 'User',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 4,
                'tenant_id' => 4,
            ],
            [
                'user_id' => 5,
                'nin_number' => '33625458701',
                'gender' => 'male',
                'phone_number' => '0807746538',
                'designation' => 'Managing Director',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 5,
                'tenant_id' => 5,
            ],
            [
                'user_id' => 6,
                'nin_number' => '33625458711',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 6,
                'tenant_id' => 6,
            ],
            [
                'user_id' => 7,
                'nin_number' => '33625458721',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Managing Director',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 7,
                'tenant_id' => 7,
            ],
            [
                'user_id' => 8,
                'nin_number' => '33625458731',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Statistician General',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 8,
                'tenant_id' => 8,
            ],
            [
                'user_id' => 9,
                'nin_number' => '33625458741',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Managing Director',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 9,
                'tenant_id' => 9,
            ],
            [
                'user_id' => 10,
                'nin_number' => '33625458751',
                'gender' => 'male',
                'phone_number' => '08067662536',
                'designation' => 'Commisioner',
                'avatar' => 'avatar.png',
                'signature' => 'signature.png',
                'department_id' => 13,
                'tenant_id' => 9,
            ],
            // [
            //     'user_id' => 11,
            //     'nin_number' => '33625458771',
            //     'gender' => 'male',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Commisioner',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 10,
            // ],
            // [
            //     'user_id' => 12,
            //     'nin_number' => '33625458781',
            //     'gender' => 'male',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Commisioner',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 11,
            // ],
            // [
            //     'user_id' => 13,
            //     'nin_number' => '33625458769',
            //     'gender' => 'male',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Commisioner',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 12,
            // ],
            // [
            //     'user_id' => 14,
            //     'nin_number' => '33625458768',
            //     'gender' => 'male',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Commisioner',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 13,
            // ],
            // [
            //     'user_id' => 15,
            //     'nin_number' => '33625458767',
            //     'gender' => 'male',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Commisioner',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 14,
            // ],
            // [
            //     'user_id' => 16,
            //     'nin_number' => '33625458766',
            //     'gender' => 'male',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Commisioner',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 15,
            // ],
            // [
            //     'user_id' => 17,
            //     'nin_number' => '33625458765',
            //     'gender' => 'male',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Commisioner',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 16,
            // ],
            // [
            //     'user_id' => 18,
            //     'nin_number' => '33625458764',
            //     'gender' => 'male',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Commisioner',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 17,
            // ],
            // [
            //     'user_id' => 19,
            //     'nin_number' => '33625458763',
            //     'gender' => 'male',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Commisioner',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 18,
            // ],
            // [
            //     'user_id' => 20,
            //     'nin_number' => '33625458762',
            //     'gender' => 'female',
            //     'phone_number' => '08067662536',
            //     'designation' => 'Confidential Secretary',
            //     'avatar' => 'avatar.png',
            //     'signature' => 'signature.png',
            //     'department_id' => null,
            //     'tenant_id' => 3,
            // ],
        ]);
    }
}
